# Generated by Django 4.2.10 on 2024-03-26 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinfnom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(default='A', max_length=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fan',
            name='sinfnom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sinfnom'),
        ),
    ]
