# Generated by Django 4.2.10 on 2024-03-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sinfnom_fan_sinfnom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='fan6',
            field=models.CharField(max_length=200),
        ),
    ]
