# Generated by Django 4.2.10 on 2024-03-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_fan_fan6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='fan6',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
